### ISSUE TITLE
When ggplot is T cannot adjust font size

### ISSUE THREAD

**Issue by namwinz** [dusadrian/venn#15] opened 2022-06-08 04:09 UTC
venn::venn(list5, ggplot = T, box = F, size = 0.5,  linetype = "dashed", ilcs=5, sncs=5) 

When ggplot is TRUE, the size of labels cannot be adjusted. Please take a look at

Thanks!

**Comment by mmahmoudian** [comment] 2022-06-08 11:26
Confirmed with version 1.10 ! Working example:

```r
tmp <- list(a = letters[1:10],
            b = letters[6:12])

venn(tmp, ilcs = 2, ggplot = F)  # works fine
venn(tmp, ilcs = 2, ggplot = T)  # does not respect the ilcs
```

**Comment by namwinz** [comment] 2022-06-08 11:37
How do increase the font size for both ilcs and sncs if I want to keep ggplot = T as object? 

Manual said ilcs and sncs should work in ggplot as well? Is there any other way to increase size if my venn diagram is a ggplot object? 

Please let me know

Thanks!

**Comment by mmahmoudian** [comment] 2022-06-08 13:50
it took me a while to realize what the issue is. This issue is because in the CRAN version the ilcs and sncs are hardcoded. This issue is fixed in https://github.com/dusadrian/venn/commit/29f58637239d162523e7928f4f29f2126fec50ca on Jun 17, 2021
. This should be fixed in the next release.

For the time being you can do the following and apply the fix:

```r
library("venn")
fix(venn)
```
then change

```r
ilcs <- 2.5
sncs <- 3.5
```

to:

```r
ilcs <- ilcs * 2.5 / 0.6
sncs <- sncs * 3.5 / 0.85
```
As shown in the screenshot below:


![image](https://user-images.githubusercontent.com/390889/172634115-9b615dfc-a921-4dc7-b46c-7fe39baa5bc0.png)

**Comment by dusadrian** [comment] 2022-06-08 20:57
Yes indeed, but that was already fixed since about 12 months ago (as noticed by @mmahmoudian), in one of the development version here, on GitHub.
It so happens the version 1.10 is about 14 months old, which means it really needs an update.

**Closed as completed by dusadrian** 2022-06-08 20:57 UTC
